import { PermissionKeys } from "../enums/permissions.enum";

export const USER_FIELD_GROUPS: Record<string, string[]> = {
    [PermissionKeys.CAN_EDIT_USER_IDENTITY]: [
        "legalName",
        "firstName",
        "lastName",
        "personalEmail",
        "gender",
        "birthday",
        "maritalStatus",
        "nationalities",
        "religion",
    ],
    [PermissionKeys.CAN_EDIT_USER_CONTACT]: [
        "workPhone",
        "personalPhone",
        "additionalPhones",
        "currentAddress",
        "homeCountryAddress",
        "homeCountryPhone",
        "emergencyContact",
    ],
    [PermissionKeys.CAN_EDIT_USER_EMPLOYMENT]: [
        "employmentDate",
        "employmentType",
        "payrollId",
        "office",
        "officeId",
        "isOutsourced",
        "hrRepresentative",
        "hrRepresentativeId",
        "level",
        "levelId",
        "manager",
        "managerId",
        "department",
        "departmentId",
        "subDepartment",
        "subDepartmentId",
        "employmentTitle",
        "employmentTitleId",
    ],
    [PermissionKeys.CAN_EDIT_USER_EDUCATION]: ["education"],
    [PermissionKeys.CAN_EDIT_USER_COMPENSATION]: ["salary"],
};
