export const USER_FIELD_GROUPS: Record<string, string[]> = {
    "userProfile:write:identity": [
        "legalName",
        "firstName",
        "lastName",
        "personalEmail",
        "gender",
        "birthday",
        "maritalStatus",
        "nationalities",
        "religion",
    ],
    "userProfile:write:contact": [
        "workPhone",
        "personalPhone",
        "additionalPhones",
        "currentAddress",
        "homeCountryAddress",
        "homeCountryPhone",
        "emergencyContact",
    ],
    "userProfile:write:employment": [
        "employmentDate",
        "employmentType",
        "payrollId",
        "office",
        "officeId",
        "isOutsourced",
        "hrRepresentative",
        "hrRepresentativeId",
        "level",
        "levelId",
        "manager",
        "managerId",
        "department",
        "departmentId",
        "subDepartment",
        "subDepartmentId",
        "employmentTitle",
        "employmentTitleId",
        "company",
        "companyId",
        "role",
    ],
    "userProfile:write:education": ["education"],
    "userProfile:write:compensation": ["salary"],
};
